[tool.poetry]
name = "flask-app-docker"
version = "0.1.0"
description = ""
authors = ["Kevin Fortier <kevin.r.fortier@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7, <4"
Flask = "^2.1.2"
requests = "^2.28.1"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^3.4"